---
version: '3.8'
services:

  rss-briefing: &rss_briefing_base
    image: rss-briefing:cpu-latest
    container_name: ${NAMESPACE}-web
    build:
      context: .
      dockerfile: Dockerfile      
    networks:
    - internal
    environment:
    - DB_UPGRADE=1
    - DB_SEED=1
    # add URL to your database
    - DATABASE_URL=${DATABASE_URL}

  rss-briefing-web:
    <<: *rss_briefing_base
    container_name: ${NAMESPACE}-webui
    networks:
    - internal
    - web
    environment:
    - DB_UPGRADE=1
    # - DB_SEED=1
    - SERVICE_PORT=${SERVICE_PORT}
    # setting secret keys
    - SECRET_FLASK_KEY=${SECRET_FLASK_KEY}
    # add URL to your database
    - DATABASE_URL=${DATABASE_URL}
    # set Flask environment: development or production (default)
    - FLASK_ENV=${FLASK_ENV}
    # choose App configs: config.DevelopmentConfig or config.ProductionConfig
    - APP_SETTINGS=${APP_SETTINGS}
    # choose custom values for seed user
    - SEED_USER=${SEED_USER}
    - SEED_PASSWORD=${SEED_PASSWORD}
    - SEED_EMAIL=${SEED_EMAIL}
    # set credentials for email backend
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_HOST_USER=${EMAIL_HOST_USER}
    - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    ports:
    - ${SERVICE_PORT}:${SERVICE_PORT}

  mysql:
    image: mysql:5.7
    container_name: ${NAMESPACE}-db
    hostname: mysql
    ports:
    - 3308:3306
    volumes:
    - db-data:/var/lib/mysql
    networks:
    - internal
    - web
    environment:
      MYSQL_DATABASE: ${RDS_DB_NAME}
      MYSQL_PASSWORD: ${RDS_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${RDS_ROOT_PASSWORD}
      MYSQL_USER: ${RDS_USERNAME}
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  db-data:
